#服务器端口配置
server:
  port: 8080

#spring相关配置
spring:
  #druid-spring-boot-starter相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  #redis相关配置
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
#日志打印
logging:
  level:
    #sql日志打印
    com.ju.mall.mbg.mapper: debug

#mybatis相关配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mbg/mapper/*
#自定义redis相关配置
redis:
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      authCode: 120 #验证码过期时间
